apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "shopport.fullname" . }}-api
  labels:
    {{- include "shopport.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: api
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "shopport.fullname" . }}
  labels:
    {{- include "shopport.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
  policyTypes: [Ingress, Egress]
  ingress:
    - from:
        - namespaceSelector: {}
      ports:
        - { protocol: TCP, port: 4000 }
  egress:
    - {}
