apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "shopport.fullname" . }}-runtime
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-weight: "-10"
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
  labels:
    {{- include "shopport.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ .Values.secrets.storeName }}
  target:
    name: {{ include "shopport.fullname" . }}-runtime
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: {{ .Values.secrets.runtimeRemoteKey }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "shopport.fullname" . }}-credentials
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-weight: "-10"
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    shopport.io/required-secret: "credentials"
  labels:
    {{- include "shopport.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ .Values.secrets.storeName }}
  target:
    name: {{ include "shopport.fullname" . }}-credentials
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: {{ .Values.secrets.credentialsRemoteKey }}
