environment: dev
appEnv: dev
app:
  nodeEnv: development
api:
  replicas: 2
  autoscaling: { minReplicas: 2, maxReplicas: 8, cpuUtilization: 65, memoryUtilization: 75 }
worker:
  minReplicas: 1
  maxReplicas: 10
secrets:
  runtimeRemoteKey: shopport-dev/runtime
  migrationRemoteKey: shopport-dev/migration
  credentialsRemoteKey: shopport-dev/credentials
